spring:
  application:
    name: registry-server
  profiles:
    active: dev
  config:
    import: optional:configserverhttp://localhost:8888
  # cloud:
  #     # uri: http://localhost:8888
  #     fail-fast: true
  #     retry:
  #       max-attempts: 20
  #       max-interval: 15000
  #       initial-interval: 10000