spring:
    application:
        name: gateway

server:
    port: 8000

eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
        client:
            service-url:
            defaultZone: http://localhost:8761/eureka/


# spring:
#     application:
#         name: gateway
#     profiles:
#         active: dev
#     config:
#         import: optional:configserver:http://localhost:8888