server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: default
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/LeonelFabianBahamonSoto/microservice-repositories.git
                    searchPaths: data-server
                    username: LeonelFabianBahamonSoto
                    password: ${PASSWORD_REPOSITORY}
                    repos:
                        team-a:
                            cloneOnStart: true
                            pattern: team-a-fabianBahamonSoto
                            searchPaths: data-server
                            uri: https://github.com/LeonelFabianBahamonSoto/microservice-repositories.git