server:
  port: 4040

spring:
  application:
    name: gateway
  profiles:
    default: eureka-off

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Activacion de endpoints
# management:
#   endpoint:
#     gateway:
#       enabled: true
#     health:
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: "*"