server:
  port: 4040

spring:
  application:
    name: gateway
  # profiles:
  #   default: eureka-on

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Activacion de endpoints
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# spring:
#   application:
#     name: ms-admin-api-gateway-server
#   profiles:
#     active: loc
#   cloud:
#     config:
#       # PARA ENTORNO DE PRODUCCION
# #      uri: http://ms-admin-config-server:8888
#       # PARA ENTORNO DE DESARROLLO
#       uri: http://localhost:8888
#       fail-fast: true
#       retry:
#          max-attempts: 20
#          max-interval: 15000
#          initial-interval: 10000