spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888


# spring:
#   application:
#     name: ms-admin-api-gateway-server
#   profiles:
#     active: loc
#   cloud:
#     config:
#       # PARA ENTORNO DE PRODUCCION
# #      uri: http://ms-admin-config-server:8888
#       # PARA ENTORNO DE DESARROLLO
#       uri: http://localhost:8888
#       fail-fast: true
#       retry:
#          max-attempts: 20
#          max-interval: 15000
#          initial-interval: 10000