spring:
  application:
    name: registry-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost