spring:
  application:
    name: report-ms

server:
  port: 7070

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

report:
  template: "{company} was founded in {foundation_date} by {founder} the websites from this company are {web_sites}"